version: "3.9"

services:

  codeql:
    image: tpf_codeql
    build:
      context: './SAST/sast/codeql'
      args:
        HOME: '/SAST'
      dockerfile: "./Dockerfile"
    volumes:
      - codeql:/codeql

  tp-framework:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: "requirements.txt"
      dockerfile: "./Dockerfile"
    env_file:
      - ./.env
    volumes:
      - codeql:/codeql
      - ./testability_patterns:/tp-framework/testability_patterns
      - ./out:/tp-framework/out
      - ./in:/tp-framework/in
    entrypoint: bash

volumes:
  codeql_interface:
  codeql: