version: "3.9"

services:

  codeql:
    image: tpf_codeql
    build:
      context: './sast/sast/codeql'
      dockerfile: "./Dockerfile"
    volumes:
      - codeql_interface:/tp-framework/SAST/codeql
      - codeql:/codeql

  tp-framework-dev:
    image: tp-framework-dev
    build:
      context: .
      args:
        REQUIREMENTS_FILE: "requirements-dev.txt"
      dockerfile: "./Dockerfile"
    env_file:
      - ./.env
    volumes:
      - codeql_interface:/tp-framework/sast/sast/codeql
      - codeql:/codeql
      - ./testability_patterns:/tp-framework/testability_patterns
      - ./out:/tp-framework/out
      - ./in:/tp-framework/in
      - ./SAST:/SAST
      - ./tp_framework:/tp-framework/tp_framework
      - ./discovery:/tp-framework/discovery
      - ./qualitytests:/tp-framework/qualitytests
    entrypoint: bash

volumes:
  codeql_interface:
  codeql: